In [1]:
import pandas as pd

In [2]:
poke = pd.read_csv('pokemon_data.csv')
poke.head() #head is the top of the list 

#remeber if you dont specify the number in the () it will just give you the first 5

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [ ]:
poke.tail() #this is the Bottom

In [ ]:
#this is the same data but loaded with excel 

df_xlsx = pd.read_excel('pokemon_data.xlsx')
df_xlsx

In [4]:
#this is with the txt (tab seperated file) 

df = pd.read_csv('pokemon_data.txt', delimiter='\t')
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [ ]:
## read the headders 
####df.columns

##read each column 
#df[['Name', 'Type 1', 'Attack']][0:5]

## read each row 
#df.iloc[1:4] ## iloc means integer location 

# this formats it diffrent 
#for index, row in df.iterrows():
    #print(index,row)

#this is condition statements 
df.loc[df['Type 1']== "Grass"]


## read a specific location (R,C)

#df.iloc[2,1]

In [5]:
#this is for stats 

df.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [6]:
df.sort_values('Name')#this will make it alphabetical

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True

In [7]:
df.sort_values(['Type 1','Name']) #this is for a list #acending for type 1 and lowest number to highest in name

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
678,617,Accelgor,Bug,NaN,80,70,40,100,60,145,5,False
182,168,Ariados,Bug,Poison,70,90,70,60,60,40,2,False
290,267,Beautifly,Bug,Flying,60,70,50,100,50,65,3,False
18,15,Beedrill,Bug,Poison,65,90,40,45,80,75,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,65,150,40,15,80,145,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
351,321,Wailord,Water,NaN,170,90,45,90,45,60,3,False
10,8,Wartortle,Water,NaN,59,63,80,65,80,58,1,False
372,340,Whiscash,Water,Ground,110,78,73,76,71,60,3,False
301,278,Wingull,Water,Flying,40,30,30,55,30,85,3,False
209,194,Wooper,Water,Ground,55,45,45,25,25,15,2,False

In [8]:
df.sort_values(['Type 1','Name'], ascending=[1,0])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
520,469,Yanmega,Bug,Flying,86,76,86,116,56,95,4,False
208,193,Yanma,Bug,Flying,65,65,45,75,45,95,2,False
288,265,Wurmple,Bug,NaN,45,45,35,20,30,20,3,False
460,413,WormadamTrash Cloak,Bug,Steel,60,69,95,69,95,36,4,False
459,413,WormadamSandy Cloak,Bug,Ground,60,79,105,59,85,36,4,False
...,...,...,...,...,...,...,...,...,...,...,...,...
11,9,Blastoise,Water,NaN,79,83,100,85,105,78,1,False
610,550,Basculin,Water,NaN,70,92,65,80,55,98,5,False
371,339,Barboach,Water,Ground,50,48,43,46,41,60,3,False
199,184,Azumarill,Water,Fairy,100,50,80,60,80,50,2,False
655,594,Alomomola,Water,NaN,165,75,80,40,45,65,5,False

In [9]:
df.sort_values('Name', ascending=False) #not alphabetical

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False

In [10]:
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [11]:
# adding the collum with the totals of all the stats

df['Total']= df['HP'] + df['Attack'] + df['Defense'] + df['Sp. Atk'] + df['Sp. Def'] + df['Speed']
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [12]:
#always good to doube check the numbers

In [13]:
#another method

 #so the first : means all of the rows everythingkinda like [:], then [4:9], but itas all within one bracket 
df['Total2'] = df.iloc[:, 4:10].sum(axis=1)
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Total2
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600,600

In [14]:
cols = list(df.columns)

df = df[cols[0:4] + [cols[-1]]+ cols[4:13]]
df

,#,Name,Type 1,Type 2,Total2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,600
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,600

## filering data

In [22]:
new_df= df.loc[(df['Type 1']== 'Grass')& (df['Type 2']=='Poison')& (df['HP']>70)] #and

new_df = new_df.reset_index()

new_df

,index,#,Name,Type 1,Type 2,Total2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,525
1,3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,625
2,50,45,Vileplume,Grass,Poison,490,75,80,85,110,90,50,1,False,490
3,77,71,Victreebel,Grass,Poison,490,80,105,65,100,70,70,1,False,490
4,652,591,Amoonguss,Grass,Poison,464,114,85,70,85,80,30,5,False,464

In [17]:
df.loc[(df['Type 1']== 'Grass')| (df['Type 2']=='Poison')] # or

,#,Name,Type 1,Type 2,Total2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,625
16,13,Weedle,Bug,Poison,195,40,35,30,20,20,50,1,False,195
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
718,650,Chespin,Grass,NaN,313,56,61,65,48,45,38,6,False,313
719,651,Quilladin,Grass,NaN,405,61,78,95,56,58,57,6,False,405
720,652,Chesnaught,Grass,Fighting,530,88,107,122,74,75,64,6,False,530
740,672,Skiddo,Grass,NaN,350,66,65,48,62,57,52,6,False,350
741,673,Gogoat,Grass,NaN,531,123,100,62,97,81,68,6,False,531

In [24]:
#looking at all the names that have MEGA 

df.loc[df['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,Total2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,625
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False,634
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False,634
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False,630
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,495
23,18,PidgeotMega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False,579
71,65,AlakazamMega Alakazam,Psychic,NaN,590,55,50,65,175,95,150,1,False,590
87,80,SlowbroMega Slowbro,Water,Psychic,590,95,75,180,130,80,30,1,False,590
102,94,GengarMega Gengar,Ghost,Poison,600,60,65,80,170,95,130,1,False,600
124,115,KangaskhanMega Kangaskhan,Normal,NaN,590,105,125,100,60,100,100,1,False,590
137,127,PinsirMega Pinsir,Bug,Flying,600,65,155,120,65,90,105,1,False,600
141,130,GyaradosMega Gyarados,Water,Dark,640,95,155,109,70,130,81,1,False,640
154,142,AerodactylMega Aerodactyl,Rock,Flying,615,80,135,85,70,95,150,1,False,615
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True,780
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,780,106,150,70,194,120,140,1,True,780
168,154,Meganium,Grass,NaN,525,80,82,100,83,100,80,2,False,525
196,181,AmpharosMega Ampharos,Electric,Dragon,610,90,95,105,165,110,45,2,False,610
224,208,SteelixMega Steelix,Steel,Ground,610,75,125,230,55,95,30,2,False,610
229,212,ScizorMega Scizor,Bug,Steel,600,70,150,140,65,100,75,2,False,600
232,214,HeracrossMega Heracross,Bug,Fighting,600,80,185,115,40,105,75,2,False,600
248,229,HoundoomMega Houndoom,Dark,Fire,600,75,90,90,140,90,115,2,False,600
268,248,TyranitarMega Tyranitar,Rock,Dark,700,100,164,150,95,120,71,2,False,700
275,254,SceptileMega Sceptile,Grass,Dragon,630,70,110,75,145,85,145,3,False,630
279,257,BlazikenMega Blaziken,Fire,Fighting,630,80,160,80,130,80,100,3,False,630
283,260,SwampertMega Swampert,Water,Ground,635,100,150,110,95,110,70,3,False,635
306,282,GardevoirMega Gardevoir,Psychic,Fairy,618,68,85,65,165,135,100,3,False,618
327,302,SableyeMega Sableye,Dark,Ghost,480,50,85,125,85,115,20,3,False,480
329,303,MawileMega Mawile,Steel,Fairy,480,50,105,125,55,95,50,3,False,480
333,306,AggronMega Aggron,Steel,NaN,630,70,140,230,60,80,50,3,False,630
336,308,MedichamMega Medicham,Fighting,Psychic,510,60,100,85,80,85,100,3,False,510
339,310,ManectricMega Manectric,Electric,NaN,575,70,75,80,135,80,135,3,False,575
349,319,SharpedoMega Sharpedo,Water,Dark,560,70,140,70,110,65,105,3,False,560
354,323,CameruptMega Camerupt,Fire,Ground,560,70,120,100,145,105,20,3,False,560
366,334,AltariaMega Altaria,Dragon,Fairy,590,75,110,110,110,105,80,3,False,590
387,354,BanetteMega Banette,Ghost,NaN,555,64,165,75,93,83,75,3,False,555
393,359,AbsolMega Absol,Dark,NaN,565,65,150,60,115,60,115,3,False,565
397,362,GlalieMega Glalie,Ice,NaN,580,80,120,80,120,80,100,3,False,580
409,373,SalamenceMega Salamence,Dragon,Flying,700,95,145,130,120,90,120,3,False,700
413,376,MetagrossMega Metagross,Steel,Psychic,700,80,145,150,105,110,110,3,False,700
418,380,LatiasMega Latias,Dragon,Psychic,700,80,100,120,140,150,110,3,True,700
420,381,LatiosMega Latios,Dragon,Psychic,700,80,130,100,160,120,110,3,True,700
426,384,RayquazaMega Rayquaza,Dragon,Flying,780,105,180,100,180,100,115,3,True,780
476,428,LopunnyMega Lopunny,Normal,Fighting,580,65,136,94,54,96,135,4,False,580
494,445,GarchompMega Garchomp,Dragon,Ground,700,108,170,115,120,95,92,4,False,700
498,448,LucarioMega Lucario,Fighting,Steel,625,70,145,88,140,70,112,4,False,625
511,460,AbomasnowMega Abomasnow,Grass,Ice,594,90,132,105,132,105,30,4,False,594
527,475,GalladeMega Gallade,Psychic,Fighting,618,68,165,95,65,115,110,4,False,618
591,531,AudinoMega Audino,Normal,Fairy,545,103,60,126,80,126,50,5,False,545
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,700

In [25]:
#dropping all the names that have mega 

df.loc[~df['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,Total2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,525
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,309
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False,405
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True,600
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,600
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,600

In [28]:
import re
df.loc[df['Type 1'].str.contains('Fire|Grass', regex=True)]

,#,Name,Type 1,Type 2,Total2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,667,Litleo,Fire,Normal,369,62,50,58,73,54,72,6,False,369
736,668,Pyroar,Fire,Normal,507,86,68,72,109,66,106,6,False,507
740,672,Skiddo,Grass,NaN,350,66,65,48,62,57,52,6,False,350
741,673,Gogoat,Grass,NaN,531,123,100,62,97,81,68,6,False,531
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,600

In [29]:
df.loc[df['Name'].str.contains('Pi[a-z]*', regex=True)]

#this is to find a certain name that starts with

,#,Name,Type 1,Type 2,Total2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
20,16,Pidgey,Normal,Flying,251,40,45,40,35,35,56,1,False,251
21,17,Pidgeotto,Normal,Flying,349,63,60,55,50,50,71,1,False,349
22,18,Pidgeot,Normal,Flying,479,83,80,75,70,70,101,1,False,479
23,18,PidgeotMega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False,579
30,25,Pikachu,Electric,NaN,320,35,55,40,50,50,90,1,False,320
136,127,Pinsir,Bug,NaN,500,65,125,100,55,70,85,1,False,500
137,127,PinsirMega Pinsir,Bug,Flying,600,65,155,120,65,90,105,1,False,600
186,172,Pichu,Electric,NaN,205,20,40,15,35,35,60,2,False,205
219,204,Pineco,Bug,NaN,290,50,65,90,35,35,15,2,False,290
239,221,Piloswine,Ice,Ground,450,100,100,80,60,60,50,2,False,450
438,393,Piplup,Water,NaN,314,53,51,53,61,56,40,4,False,314
558,499,Pignite,Fire,Fighting,418,90,93,55,70,55,55,5,False,418
578,519,Pidove,Normal,Flying,264,50,55,50,36,30,43,5,False,264
716,648,MeloettaPirouette Forme,Normal,Fighting,600,100,128,90,77,77,128,5,False,600

# conditional chages

In [31]:
df.loc[df['Type 1'] == 'Fire', 'Type 1']= 'Flamer'

df

,#,Name,Type 1,Type 2,Total2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,625
4,4,Charmander,Flamer,NaN,309,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,600
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Flamer,Water,600,80,110,120,130,90,70,6,True,600

## Aggregate Statistics (Group by)

In [33]:
df.groupby(['Type 1']).mean()

,#,Total2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
Type 1,,,,,,,,,,,
Bug,334.492754,378.927536,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,3.217391,0.000000,378.927536
Dark,461.354839,445.741935,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,4.032258,0.064516,445.741935
Dragon,474.375000,550.531250,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,3.875000,0.375000,550.531250
Electric,363.500000,443.409091,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,3.272727,0.090909,443.409091
Fairy,449.529412,413.176471,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,4.117647,0.058824,413.176471
Fighting,363.851852,416.444444,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,3.370370,0.000000,416.444444
Flamer,327.403846,458.076923,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,3.211538,0.096154,458.076923
Flying,677.750000,485.000000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,5.500000,0.500000,485.000000
Ghost,486.500000,439.562500,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,4.187500,0.062500,439.562500
Grass,344.871429,421.142857,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,3.357143,0.042857,421.142857
Ground,356.281250,437.500000,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,3.156250,0.125000,437.500000
Ice,423.541667,433.458333,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,3.541667,0.083333,433.458333
Normal,319.173469,401.683673,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,3.051020,0.020408,401.683673
Poison,251.785714,399.142857,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,2.535714,0.000000,399.142857
Psychic,380.807018,475.947368,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,3.385965,0.245614,475.947368
Rock,392.727273,453.750000,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,3.454545,0.090909,453.750000
Steel,442.851852,487.703704,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,3.851852,0.148148,487.703704
Water,303.089286,430.455357,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,2.857143,0.035714,430.455357